$DESIGN_DIR/program_counter.sv
$VERIFICATION_DIR/program_counter_test/driver.sv
$VERIFICATION_DIR/program_counter_test/monitor.sv
$VERIFICATION_DIR/program_counter_test/program_counter_interface.sv
$VERIFICATION_DIR/program_counter_test/environment.sv
$VERIFICATION_DIR/program_counter_test/test.sv
$VERIFICATION_DIR/program_counter_test/program_counter_tb.sv
